[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  base = "."

[dev]
  command = "npm run dev"
  publish = "dist"
  targetPort = 4321
  port = 8888
  autoLaunch = false